import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import BreadCrumb from '../components/breadCrumb'
import Browse from '../components/browse'
import Hero from '../components/hero'
import Locales from '../components/locales'
import Pagination from '../components/pagination'
import Popular from '../components/popular'
import Search from '../components/search'
import { connectToDatabase } from '../lib/mongodb'
import styles from '../styles/Home.module.css'

export default function Home({ locales,popular_words }) {
  const router = useRouter();
  const locales_parsed = JSON.parse(locales)
  const p_words_parsed = JSON.parse(popular_words)
  

  let current_page = router.query.page;

  const breadcrum_items = [
    {
      name:"Home",
      href:"/"
    }
  ]
  return (
    <div>
      <Head>
        <title>Word Book</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
        <meta name="msapplication-TileColor" content="#da532c"/>
        <meta name="theme-color" content="#ce4949"/>
      </Head>
      <main>
      <BreadCrumb breadcrum_items={breadcrum_items}/>
      <Hero/>
      <div className="my-4"></div>
      <Search enableAutoSubmit={false}/>
      <div className="my-4"></div>
      <Locales languages={locales_parsed}/>
      <div className="my-4"></div>
      <Popular words={p_words_parsed}/>
      
      <Browse page_type={`browse`} selected={null}/>
      </main>
    </div>
  )
}


export async function getStaticProps() {


  const { db } = await connectToDatabase();

  const l = await db.collection("locales").find({}).toArray()
  const locales = JSON.stringify(l)
  
  const popular_words = JSON.stringify(
    await db
      .collection(process.env.DATA_COLLECTION)
      .find({})
      .project({word: 1})
      .sort({views:-1})
      .limit(30)
      .toArray()
  );


  return {
    props: {locales,popular_words},revalidate: 10,
  }
}



