import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Browse from '../components/browse'
import Hero from '../components/hero'
import Locales from '../components/locales'
import Pagination from '../components/pagination'
import Popular from '../components/popular'
import Search from '../components/search'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();

  let current_page = router.query.page;
  return (
    <div>
      <Head>
        <title>Word Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Hero/>
      <div className="my-4"></div>
      <Search/>
      <div className="my-4"></div>
      <Popular/>
      <div className="my-4"></div>
      <Locales/>
      <Browse page_type={`browse`} selected={"a"}/>
      </main>
    </div>
  )
}
